version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
      - run: apk add make curl bash
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: docker buildx version
      - run: docker context create cictx
      - run: docker buildx create cictx --platform linux/amd64,linux/arm64 --use
      - run: docker buildx ls
      - run: ./build-images.sh

workflows:
  version: 2
  build_test_push_deploy:
    jobs:
      - build:
          context: arangodboasis
