version: 2.1
jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
      - run: apk add make curl bash
      - run: ./build-images.sh

workflows:
  version: 2
  build_test_push_deploy:
    jobs:
      - build:
          context: arangodboasis
