version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ./build-images.sh

workflows:
  version: 2
  build_test_push_deploy:
    jobs:
      - build:
          context: arangodboasis
