version: 2.1
jobs:
  build:
    docker: 
    - image: cimg/base:2021.10
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build-images.sh

workflows:
  version: 2
  build_test_push_deploy:
    jobs:
      - build:
          context: arangodboasis
